name: Node.js CI

on:
  push:
    branches:
      - main

jobs:
  build:
    permissions:
      contents: read
      id-token: write
      pages: write

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          cache: npm
          node-version: "20.x"

      - run: npm ci
      - run: npm run build
      - run: npm test

      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@v3.0.1
        with:
          path: build/

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4.0.5
